on: [push]	
name: Test	
jobs:	
  test:	
    strategy:	
      matrix:	
        go-version: [1.13.x]	
        platform: [ubuntu-latest]	
    runs-on: ${{ matrix.platform }}	
    steps:	
      - name: Install libfido2
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install software-properties-common
          sudo apt-add-repository ppa:yubico/stable
          sudo apt update
          sudo apt install libfido2-dev
      - name: Install Go	
        uses: actions/setup-go@v1	
        with:	
          go-version: ${{ matrix.go-version }}	
      - name: Checkout code	
        uses: actions/checkout@v2	
      - name: Test	
        run: go test	
        env:	
          LD_LIBRARY_PATH: ./linux/lib	
          DYLD_LIBRARY_PATH: ./darwin/lib	
          PATH: ./windows/lib
